apiVersion: v1
kind: Pod
metadata:
  name: laravel-pod
  labels:
    app: laravel-app
spec:
  containers:
    - name: web
      image: php:8.2-fpm
      ports:
        - containerPort: 8080
        - containerPort: 22
      volumeMounts:
        - name: laravel-data
          mountPath: /var/www/html

    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: laravel-data
          mountPath: /var/www/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d

    - name: mysql
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Hello@123"
        - name: MYSQL_DATABASE
          value: "bopha-db"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

  volumes:
    - name: laravel-data
      emptyDir: {}
    - name: nginx-config
      configMap:
        name: nginx-config
    - name: mysql-data
      emptyDir: {}
